# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

# GoReleaser configuration for flo.
# Builds cross-platform binaries (linux, darwin, windows) for amd64 and arm64,
# then publishes to GitHub Releases and auto-taps into Homebrew.

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: flo
    main: ./main.go
    binary: flo
    # Inject version at build time via ldflags.
    ldflags:
      - -s -w -X github.com/ratnesh-maurya/flo/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: flo
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # Use zip for Windows.
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

# Homebrew cask configuration.
# On release, GoReleaser will create/update the cask at:
#   ratnesh-maurya/homebrew-tap/Casks/flo.rb
homebrew_casks:
  - name: flo
    repository:
      owner: ratnesh-maurya
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/ratnesh-maurya/flo"
    description: "Search Stack Overflow from your terminal using the MCP protocol"
    license: "MIT"
    binaries:
      - flo
